### ISSUE TITLE
Error with "click" when mass searching

### ISSUE THREAD

**Issue by ghost** [KeironO/dimedbpy#1]
Getting an error with attempting to use the mass search function, using python 2.7.8 and click 7:
```python
from dimedbpy import mass_search
search = mass_search(100)
```

```python
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    search = mass_search(100)
  File "/Users/nunen/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nunen/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/core.py", line 703, in main
    args = list(args)
TypeError: 'int' object is not iterable
```
Putting it in as a string or a float doesn't help either. When I leave the function empty (just mass_search()) it works fine. 

I've temporarily resolved it by simply removing the 4 lines about Click above the function in __init__.py.

**Comment by KeironO** [comment]
Hey there,

Apologies about the lack of response. I'm currently working on getting the final release of DIMEdb out, so time is a little scarce. I will attempt to resolve this issue this evening.

Hardly anybody uses the click interface, so I'm probably going to depreciate that.

Regards,

Keiron

**Comment by KeironO** [comment]
So, I finally go around to doing this.

The new release should fix any issues related to this. I know a lot of people didn't have them, but I was able to reproduce today so I got around to fixing it.
